<h3 align="center">Willkommen im Admin-Bereich!</h3>

<p>
Dies ist der Administrations-Bereich von SimpleCMS v08/15<br>
&nbsp;<br>
Von hier aus lassen sich wichtige Bereiche der Website bearbeiten.<br>
&nbsp;<br>
Falls Sie Fragen oder Probleme zu bzw. mit diesem Admin-Breich haben, schreiben Sie uns. Unsere eMail-Adresse lautet: <a href="mailto:info@wexelwirken.net?subject=Admin-Bereich SimpelCMS v08/15">info@wexelwirken.net</a>.<br>
</p>